{% set name = "pycuda" %}
{% set version = "2019.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycuda-{{ version }}.tar.gz
  sha256: ada56ce98a41f9f95fe18809f38afbae473a5c62d346cfa126a2d5477f24cc8a

build:
  number: 0
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - cudatoolkit-dev
    - wget # cudatoolkit needs it
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - numpy >=1.6
    - pip
    - python
    - cudatoolkit-dev
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - appdirs >=1.4.0
    - decorator >=3.2.0
    - mako
    - python
    - pytools >=2011.2
    - cudatoolkit-dev
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pycuda
    - pycuda.compyte
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://mathema.tician.de/software/pycuda
  summary: Python wrapper for Nvidia CUDA
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - abonawas
